---
title: " "
---

# Azzurri忘年会\@さっぽろ (2019)

## １次会

- 1次会は3500円前後のイメージ
    - 人数は20~40人で見とけば大丈夫そう
    - 座席の増減が効く貸切が理想ですね

## ビンゴ大会 -> くじ引き大会？

- じゅんさん基金 (2–3万円) を使用
    - とりあえずで書いたら余りそう
    - 余ったら２次会にでも

- <i class="fas fa-star"></i> 7000円 ✕ 1人
    - ゲームシャツ
- <i class="fas fa-futbol"></i> 1500円 ✕ 3人
    - 筋トレグッズだと女性陣が少し寂しいかもなので選択肢から選べるシステムがいい？
    - プロテイン500 g
    - ちっちゃいボール ([これは高いけどこんなの](http://www.quebra-ws.com/shopdetail/000000038351/164/007/Y/page1/disp_pc/))
    - 靴紐とか
- <i class="fas fa-question"></i> 1000円 ✕ 5人
    - フットサル関係ないものでもいいかも (逆に悩む)

## おみせ候補


```{r, include = FALSE, echo = FALSE}
library(tidyverse)
library(leaflet)
library(htmlwidgets)
library(DT)


# known <-
#   tibble(name = c("蕎麦切り 黒むぎ",
#                   "Bistro CinqCes ビストロサンクシー",
#                   "金丸農園 野菜居酒屋ルンゴカーニバル"),
#          station = c("JR札幌", "西8丁目", "JR札幌"),
#          lat = c(43.070994, 43.057606, 43.069536),
#          lon = c(141.348435, 141.348112,  141.348381),
#          class = c("c", "b", "b"),
#          url = c("https://tabelog.com/hokkaido/A0101/A010101/1041095/",
#                  "https://tabelog.com/hokkaido/A0101/A010103/1007160/",
#                  "https://tabelog.com/hokkaido/A0101/A010101/1039619/"),
#          memo = c("和。2h 4000円~, 非常によかったが落ち着いているので気が引ける。",
#                   "仏。2h 3500~4000円, ワインが充実、部分的に貸し切って20人くらいで利用した。",
#                   "欧？2h 3500~4000円, 誕生日ケーキサービスなどパリピ感があった。")) %>%
#   mutate(name = paste0(name, " <a href=", url, " target='_top'>web</a><br>", memo))
# unknown <-
#   tibble(name = c("カジュアル スパニッシュイタリアン エスパニョール",
#                   "肉バル ミートボーイN.Y",
#                   "Oyster&Steak DINER es",
#                   "イタリア居酒屋Bocco",
#                   "とりっくす",
#                   "お鍋と炭焼き居酒屋  URARA",
#                   "ワインとお酒、フレンチおでん　ビストロバンバン",
#                   "北海道ろばた居心地"),
#          station = c("JR札幌/大通り", "JR札幌/大通り", "JR札幌/大通り", "すすきの", "すすきの", "すすきの", "西８丁目", "すすきの"),
#          lat = c(43.066069, 43.067035, 43.066997, 43.053978, 43.056776, 43.056192, 43.057753, 43.057281),
#          lon = c(141.352930, 141.353231, 141.353188, 141.355010, 141.354247, 141.352114, 141.346508, 141.351464),
#          class = c("a", "a", "b", "a", "b", "a", "b"),
#          url = c("https://www.hotpepper.jp/strJ000747942/",
#                  "https://www.hotpepper.jp/strJ001009952/",
#                  "https://www.hotpepper.jp/strJ000989880/",
#                  "https://www.hotpepper.jp/strJ000707076/",
#                  "https://www.hotpepper.jp/strJ000999523/",
#                  "https://www.hotpepper.jp/strJ000717037/",
#                  "https://www.hotpepper.jp/strJ000861385/",
#                  "https://www.hotpepper.jp/strJ001028582/"),
#          memo = c("西・伊。2h 3100円~, 20人、30人個室。店名が迷走している。アルコールいまいちかも。",
#                   "米？2h 3000円~, チーズフォンデュ。30人テーブル。",
#                   "欧？2h 3600~4000円, フロアで複数テーブルに分散。やや品目少ないがアルコール揃いがいい。",
#                   "伊。2h 3000円~, こじんまりっぽい、テーブル18人、個室36人。",
#                   "博多。2h 3500円, 半個室24人テーブル。非常に当たり障りがない。",
#                   "和。2h 3000円, 焼き鳥・串焼き系の食べ放題、22人個室。レビューを見るに対応は早いらしい。",
#                   "仏+おでん。2h 3500円, 2F貸し切り20~名、店舗貸し切り30~40名、もしかしたら階わかれるかも。",
#                   "海鮮。2h 3500円, フロア半貸し切り25人~、30人〜で店舗貸し切り、MAX68人なので結構ゆったり。"
#                   )) %>%
#   mutate(name = paste0(name, " <a href=", url, " target='_top'>web</a><br>", memo))
# 
# mame <-
#   tibble(name = c("梅酒 焼酎だいにんぐ かくれんぼ",
#                   "焼肉バル BAR carne alla griglia（カルネアラグリーリア）"),
#          station = c("すすきの", "すすきの"),
#          lat = c(43.058125, 43.056616),
#          lon = c(141.357314, 141.354360),
#          class = c("b", "b"),
#          url = c("https://www.hotpepper.jp/strJ000728152/",
#                  "https://www.hotpepper.jp/strJ001018019/"),
#          memo = c("和。2h 3500円~, 梅酒&焼酎が豊富。テーブル席で45人。",
#                   "西。2h 3500円~, 内装がおしゃれ〜。パーティ仕様で最大40人。")) %>%
#   mutate(name = paste0(name, " <a href=", url, " target='_top'>web</a><br>", memo))

color_set <-
  c("orange", "red", "darkred")
color_set_map <-
  list("<FONT color='orange'>3000円</FONT>",
       "<FONT color='red'>3500円</FONT>",
       "<FONT color='darkred'>4000円</FONT>")

restaurant <-
  read_csv("~/Dropbox/page/data/restaurant/sapporo_over30.csv") %>%
  mutate(name = paste0("<a href=", url, " target='_top'>", name, "</a> | ", category, "<br>", memo))

add_group_marker <-
  function(.map, tbl, is_known){
    .map %>%
    addCircleMarkers(data = filter(tbl, class == "a"), fillColor = is_known, fillOpacity = .75,
                     # clusterId = 1, clusterOptions = markerClusterOptions(),
                     lng = ~lon, lat = ~lat, popup = ~ name, radius = 5,
                     color = color_set[1], group = color_set_map[[1]]) %>%
    addCircleMarkers(data = filter(tbl, class == "b"), fillColor = is_known, fillOpacity = .75,
                     # clusterId = 1, clusterOptions = markerClusterOptions(),
                     lng = ~lon, lat = ~lat, popup = ~ name, radius = 5,
                     color = color_set[2], group = color_set_map[[2]]) %>%
    addCircleMarkers(data = filter(tbl, class == "c"), fillColor = is_known, fillOpacity = .75,
                     # clusterId = 1, clusterOptions = markerClusterOptions(),
                     lng = ~lon, lat = ~lat, popup = ~ name, radius = 5,
                     color = color_set[3], group = color_set_map[[3]]) %>%
    return()
  }


bounenkai <-
  leaflet() %>%
  addProviderTiles(providers$CartoDB) %>%
  add_group_marker(restaurant, is_known = "white") %>%
  # add_group_marker(known, is_known = "pink") %>%
  # add_group_marker(unknown, is_known = "black") %>%
  # add_group_marker(mame, is_known = "black") %>%
  addLayersControl(
    overlayGroups = c(color_set_map[[1]], color_set_map[[2]], color_set_map[[3]]),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  # addLegend("topright",
  #           title= "貸切可能人数", 
  #           values = ~ price,
  #           colors =c("grey25", "grey", "black"),
  #           labels= c("15人~", "25人~", "30人~"),
  #           opacity = 1) %>%
  return()

bounenkai

dir.create("leaflet", showWarnings = FALSE)
setwd("leaflet")
saveWidget(bounenkai, "bounenkai_map.html", selfcontained = T)
setwd("..")
```

```{r, results="asis", echo = FALSE}
restaurant %>%
  transmute(` ` = name, 駅 = station, 貸切 = style, 定員 = capacity) %>%
  datatable(escape = FALSE, rownames = FALSE, options = list(dom = 'tp'))
```

<br>

<iframe seamless src="../leaflet/bounenkai_map/index.html" width="95%" height="400px"></iframe>
