---
title: " "
---

<FONT color="grey">Last update: `r lubridate::now()`  </FONT><br>

```{r, message = F, echo = F, warning = F}
library(fudukue)

del_link <- F
add_if <- F

  # Record generator
ToRecord <-
  function(number = "", title, authors, year, in_what, type, url = NULL){
    if(url == "" | del_link) {
      c(No = number,
        Title = paste0(title, "<br>&emsp;", authors),
        Year = year,
        In = in_what,
        Type = type)
    } else {
      c(No = number,
        Title = paste0("<a href = '", url, "' target='_blank'>", title, "</a><br>&emsp;", authors),
        Year = year,
        In = in_what,
        Type = type)
    }
  }

# Table generator
ToKable <-
  function(PublicationList, in_what){
  PublicationList %<>%
      matrix(byrow = T, ncol = 5)
  colnames(PublicationList) = c('No', 'Title', 'Year', 'Category', in_what)
  PublicationList %>%
    data.frame %>%
    # arrange(desc(Year), Category) %>%
    arrange(desc(No), desc(Year), Category) %>%
    rename(` ` = No) %>%
    kable
  }

speaker <- function(text) paste0("<sup>○</sup>", text)
correspond <- function(text) paste0(text, "<sup>+</sup>")
new_item <- function(text) paste0("<FONT color='red'><sup>New </sup></FONT>", text)
coming_item <- function(text) paste0("<FONT color='grey'>", text, "</FONT>")

# Frequently appears
KM <- "<FONT color='green'>Keach Murakami</FONT>"
RM <- "Ryo Matsuda"
KF <- "Kazuhiro Fujiwara"
YI <- "Yasuomi Ibaraki"

KM_ <- "<FONT color='green'>村上 貴一</FONT>"
RM_ <- "松田 怜"
KF_ <- "富士原 和宏"
YI_ <- "荊木 康臣"

```


```{r journal, message = F, echo = F, warning = F}
impacts <-
  Vectorize(ifelse)(add_if, paste0("<br><FONT color='grey'>IF: ", c(0.467, 2.216, 3.520, 1.538, NA, 6.169, 3.330, 4.760), "</FONT>"), "")

original_articles <-
  c(
    ToRecord(
      "001",
      "Effects of supplemental lighting to a lower leaf using light-emitting diodes with different spectra on the leaf photosynthetic rate in sweet pepper",
      paste(KM, correspond(RM), KF, sep = ", "),
      "2013",
      "Original Article",
      paste0("Journal of Agricultural Meteorology", impacts[1]),
      "https://www.jstage.jst.go.jp/article/agrmet/69/2/69_69.2.2/_article"),
    
     ToRecord(
       "002",
       "Light-induced systemic regulation of photosynthesis in primary and trifoliate leaves of <i>Phaseolus vulgaris</i>: effects of photosynthetic photon flux density (PPFD) <i>versus</i> spectrum",
       paste(KM, correspond(RM), KF, sep = ", "),
       "2014",
       "Original Article",
       paste0("Plant Biology", impacts[2]),
       "http://onlinelibrary.wiley.com/wol1/doi/10.1111/plb.12055/abstract"),
     
    ToRecord(
      "003",
      "Interaction between the spectral photon flux density distributions of light during growth and for measurements in net photosynthetic rates of cucumber leaves",
      paste(correspond(KM), RM, KF, sep = ", "),
      "2016",
      "Original Article",
      paste0("Physiologia Plantarum", impacts[3]),
      "http://onlinelibrary.wiley.com/wol1/doi/10.1111/ppl.12421/abstract"),
    
    ToRecord(
      "004",
      "Quantification of excitation energy distribution between photosystems based on a mechanistic model of photosynthetic electron transport",
      paste(correspond(KM), correspond(RM), KF, sep = ", "),
      "2018",
      "Original Article",
      paste0("Plant, Cell & Environment", impacts[6]),
      "http://onlinelibrary.wiley.com/wol1/doi/10.1111/pce.12986/abstract"),
    
    ToRecord(
      "005",
      new_item("A mathematical model of photosynthetic electron transport in response to light spectrum based on excitation energy distributed to photosystems"),
      paste(correspond(KM), correspond(RM), KF, sep = ", "),
      "In press",
      "Original Article",
      paste0("Plan and Cell Physiology", impacts[7]),
      "http://dx.doi.org/10.1093/pcp/pcy085"),

    ToRecord(
      "006",
      new_item("Time course of the photochemical reflectance index (PRI) during photosynthetic induction: its relationship with the photochemical yield of photosystem II"),
      paste(correspond(KM), YI, sep = ", "),
      "In press",
      "Original Article",
      paste0("Physiologia Plantarum", impacts[8]),
      "http://dx.doi.org/10.1111/ppl.12745")
  )

other_articles <-
  c(
    ToRecord(
      "co-authored",
      "Effects of spectral distribution and photosynthetic photon flux density for overnight LED light irradiation on tomato seedling growth and leaf injury",
      paste(correspond(RM), "Takuto Yamano", KM, KF, sep = ", "),
      "2016",
      "Original Article",
      paste0("Scientia Horticulturae", impacts[4]),
      "http://www.sciencedirect.com/science/article/pii/S0304423815303198"),
      
    ToRecord(
      "letter",
      "A basis for selecting light spectral distribution for evaluating leaf photosynthetic rates of plants grown under different light spectral distributions",
      paste(correspond(KM), RM, KF, sep = ", "),
      "2017",
      "letter",
      paste0("Environmental Control in Biology", impacts[5]),
      "https://www.jstage.jst.go.jp/article/ecb/55/1/55_1/_article")
  )
```

```{r books, message = F, echo = F}
books <-
  c(
    ToRecord(
      "01",
      "Light- and CO<sub>2</sub>-dependent systemic regulation of photosynthesis",
      paste(correspond(RM), KM, sep = ", "),
      "2016",
      "Book chapter<br>(peer-reviewd)",
      "Progress in Botany",
      "http://www.springer.com/in/book/9783319256863"),
    
    ToRecord(
      "02",
      "Optical and physiological properties of a leaf",
      paste(correspond(KM), RM, sep = ", "),
      "2016",
      "Book chapter",
      "LED Lighting for Urban Agriculture",
      "http://www.springer.com/us/book/9789811018466")
  )
```

```{r symposiums_international, message = F, echo = F}
symp_int <-
  c(  
    ToRecord(
      "04",
      new_item("Spectral imaging for evaluation of spatial distributions of leaf photosynthetic light use efficiency"),
      paste(speaker(KM), YI, sep = ", "),
      "2018",
      "Oral",
      "IHC2018.<br>Istanbul, Turkey, 2018/08/12-2018/08/16",
      ""),
    
    ToRecord(
      "03",
      "Non-destructive estimation of light energy distribution between photosystems",
      paste(speaker(KM), RM, KF, sep = ", "),
      "2016",
      "Oral",
      "ICEC/AusPheno 2016.<br>Canberra, Australia. 2016/09/18-2016/09/23",
      ""),
    
    ToRecord(
      "02",
      "A difference in net photosynthetic rate between leaves grown with and without far-red light depends on the spectral distribution of measuring light",
      paste(speaker(KM), RM, KF, sep = ", "),
      "2015",
      "Poster",
      "GreenSys 2015.<br>Évora, Portugal. 2015/07/19-2015/07/23",
      ""),
    
    ToRecord(
      "01",
      "Effect of supplemental lighting to a lower leaf using LEDs with different wavelengths on leaf photosynthetic characteristics in sweet pepper",
      paste(speaker(KM), RM, KF, sep = ", "),
      "2012",
      "Poster",
      "7th International Symposium on Light in Horticultural Systems (LightSym 2012).<br>Wageningen, The Netherlands. 2012/10/15-2012/10/18",
      "")
  )
```

```{r symposiums_domestic, message = F, echo = F}
symp_domestic <-
  c(
    ToRecord(
      "014",
      "深層学習を用いた葉面積推定に関する研究",
      paste(speaker(YI_), "水畑 順太", KM_, sep = ", "),
      "2018",
      "Oral",
      "日本農業気象学会 2018 年全国大会<br>@九大伊都, 2018/03/13-2018/03/17",
      ""),
    
    ToRecord(
      "015",
      "分光画像計測による光合成速度分布解析の試み",
      paste(speaker(KM_), YI_, sep = ", "),
      "2018",
      "Oral",
      "日本農業気象学会 2018 年全国大会<br>@九大伊都, 2018/03/13-2018/03/17",
      ""),

    ToRecord(
      "013",
      "分光反射画像計測による葉位別光合成速度推定にむけて: PRIの光応答の評価",
      paste(speaker(KM_), YI_, sep = ", "),
      "2017",
      "Oral",
      "日本農業気象学会 中国四国支部大会<br>@鳥大, 2017/12/07-2017/12/08",
      ""),
    
    ToRecord(
      "012",
      "葉面反射画像計測による光合成光利用効率の光環境変化に対する応答の評価の試み",
      paste(speaker(KM_), YI_, sep = ", "),
      "2017",
      "Oral",
      "日本生物環境工学会 2017 年松山大会<br>@愛媛大樽味, 2017/08/30-2017/09/04",
      ""),

    ToRecord(
      "011",
      "光化学系I・II間での励起エネルギー分配比の非破壊定量法の開発",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2017",
      "Poster",
      "第 8 回日本光合成学会年会<br>@龍谷大瀬田, 2017/05/27-2017/05/28",
      ""),

    ToRecord(
      "010",
      "夜間に照射する LED 光の分光分布および PPFD がトマト苗の成育および可視障害に及ぼす影響",
      paste(speaker(RM_), "山埜 拓人", KM_, KF_, sep = ", "),
      "2016",
      "Oral",
      "日本農業気象学会 2016 年全国大会<br>@岡山大, 2016/03/14-2016/03/17",
      ""),
    
    ToRecord(
      "009",
      "サンプルサイズ（<i>n</i>）の検定力分析による決定 ―グロースチャンバでの植物栽培試験での例—",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2016",
      "Poster",
      "日本農業気象学会 2016 年全国大会<br>@岡山大, 2016/03/14-2016/03/17",
      ""),
    
    ToRecord(
      "008",
      "栽培中の遠赤色光添加は栽培後の葉の光合成速度を小さくするのか？",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2015",
      "Oral",
      "日本生物環境工学会 2015 年宮崎大会<br>@シーガイア(宮崎), 2015/09/08-2015/09/11",
      ""),
    
    ToRecord(
      "007",
      "異なる分光分布の光照射下で成育した葉の光合成速度比較結果は測定光分光分布に影響される",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2015",
      "Oral",
      "日本農業気象学会 2015 年全国大会<br>@文部科学省研究交流センター(つくば), 2015/03/16-2015/03/19",
      ""),
    
    ToRecord(
      "006",
      "異なる狭波長帯 LED 光の混合照射下における個葉の総光合成速度の推定",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2014",
      "Poster",
      "第 5 回日本光合成学会年会<br>@近畿大奈良, 2014/05/30-2014/05/31",
      ""),
  
    ToRecord(
      "005",
      "下位葉補光・終夜補光の光質が植物の光合成特性と成育に及ぼす影響",
      paste(speaker(RM_), "山埜 拓人", KM_, KF_, sep = ", "),
      "2014",
      "Oral",
      "日本農業気象学会 2014 年全国大会<br>@北大, 2014/03/18-2014/03/21",
      ""),
    
    ToRecord(
      "004",
      "種々のピーク波長の LED を用いた混合光照射下におけるコスレタス葉の光合成量子収率",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2014",
      "Oral",
      "日本農業気象学会 2014 年全国大会<br>@北大, 2014/03/18-2014/03/21",
      ""),
    
    ToRecord(
      "003",
      "異なるピーク波長の LED を用いた混合光照射下における個葉の光合成量子収率",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2013",
      "Oral",
      "日本生物環境工学会 2013 年香川大会<br>@香川大, 2013/09/02-2013/09/05",
      ""),
    
    ToRecord(
      "002",
      "インゲンマメ下位葉への単色 LED 光照射が上位葉の光合成特性に及ぼす影響",
      paste(speaker(KM_), RM_, KF_, sep = ", "),
      "2012",
      "Oral",
      "日本生物環境工学会 2012 年東京大会<br>@東大弥生, 2012/09/04-2012/09/07",
      ""),
    
    ToRecord(
      "001",
      "トマト養液栽培における葉面積指数推定モデルの構築: 気孔コンダクタンスモデルの検討",
      paste(speaker(RM_), KM_, KF_, sep = ", "),
      "2012",
      "Poster",
      "日本農業気象学会 2012 年全国大会<br>@大阪府大中百舌鳥, 2012/03/13-2012/03/17",
      "")
  )
```

<!-- #### 業績一覧 -->

<!-- #### 村上 貴一 (生物環境工学研究室) -->

<!-- <br> -->

<!-- ##### 査読付き論文 -->


<!-- ##### 英文書籍 -->

<!-- - `r length(books)/4`件 -->
<!--     - 筆頭での執筆: 1件 -->

<!-- ##### 国際学会 -->

<!-- - `r length(symp_int)/4`件 -->
<!--     - 筆頭での口頭発表: 1件 -->
<!--     - 筆頭でのポスター発表: 2件 -->

<!-- ##### 国内学会 -->

<!-- - `r length(symp_domestic)/4`件 -->
<!--     - 筆頭での口頭発表: 5件 -->
<!--     - 筆頭でのポスター: 2件 -->

--------------

<br>
<sup>+</sup> -> Corresponding Author  
<!-- <sup>1st</sup> -> First Author -->

### Journal Articles

#### Original and first-author

```{r, message = F, echo = F, warning = F}
original_articles %>%
  ToKable(in_what = "Journal")
```

<br>

#### Others

```{r, message = F, echo = F, warning = F}
other_articles %>%
  ToKable(in_what = "Journal")
```

<br>

-----

### Book Chapters

```{r, message = F, echo = F}
books %>%
  ToKable(in_what = "Book")
```
  
<br>

--------------

<br>
<sup>○</sup> -> Speaker  

### Presentations in International Academic Conferences

```{r, message = F, echo = F}
symp_int %>%
  ToKable(in_what = "Venue Date")
```

<br>


### Presentations in Domestic Academic Conferences

```{r, message = F, echo = F}
symp_domestic %>%
  ToKable(in_what = "Venue Date")
```

----

```{r eval = F, echo = F}
# rmarkdown::render("~/Dropbox/KeachMurakami.github.io/PublicationList.Rmd")
# knit(input = "~/Dropbox/KeachMurakami.github.io/PublicationList.Rmd",
#      output = "~/Dropbox/KeachMurakami.github.io/PublicationList.md")
```

```{r map, echo = F, eval = F}
library(leaflet)

work_location <-
  data.frame(
    name = c("東大環境研", "山口大荊木研"),
    lat = c(35.7167, 34.1492),
    lng = c(139.7616, 131.4691),
    from = c("2012/Apr", "2017/Apr"),
    to = c("2017/Mar", "2020/Mar")
  ) %>%
  mutate(popup=paste(name, "<br/>", from, "--", to))
  # mutate(popup=paste(sprintf('<a href="%s">%s</a>', url, name), opens, major, sep="<br/>"))


# name, lat, lng, from, to, url

# ECB
`_symp_ecb2012` <- c("日本生物環境工学会@東大", 35.7167, 139.7616, "2012-09-04", "2012-09-07", "")
`_symp_ecb2013` <- c("日本生物環境工学会@香川大", 34.3428, 134.0380, "2013-09-02", "2013-09-05", "")
`_symp_ecb2014` <- c("日本生物環境工学会@明治大御茶ノ水", 35.697224, 139.761536, "2014-09-09", "2014-09-11", "")
`_symp_ecb2015` <- c("日本生物環境工学会@宮崎", 31.9603, 131.4704, "2015-09-08", "2015-09-11", "")
`_symp_ecb2017` <- c("日本生物環境工学会@愛媛大樽味", 33.8389, 132.7919, "2017-08-30", "2017-09-04", "")

# AgrMet
`_symp_agrmet2014` <- c("日本農業気象学会全国大会@北大", 43.0719, 141.3449, "2014-03-18", "2014-03-21", "")
`_symp_agrmet2015` <- c("日本農業気象学会全国大会@つくば", 36.074657, 140.117862, "2015-03-16", "2015-03-19", "")
`_symp_agrmet2016` <- c("日本農業気象学会全国大会@岡山大津山", 34.6874, 133.9222, "2016-03-14", "2016-03-17", "")
`_symp_agrmet2017` <- c("日本農業気象学会全国大会@北里大十和田", 40.6242, 141.2379, "2017-03-14", "2017-03-17", "-")
`_symp_agrmet2017block` <- c("日本農業気象学会 中国四国支部大会", 35.5152, 134.1734, "2017-12-07", "2017-12-08", "")

# Photosynthesis
`_symp_photosyn2014` <- c("日本光合成学会年会@近畿大奈良", 34.6720, 135.7325, "2014-05-30", "2014-05-31", "")
`_symp_photosyn2015` <- c("日本光合成学会年会@岡山", 34.6682, 133.9164, "2015-05-22", "2015-05-23", "-")
`_symp_photosyn2017` <- c("日本光合成学会年会@龍谷大瀬田", 34.9642, 135.9405, "2017-05-27", "2017-05-28", "")

# Horticulture
`_symp_hort2015spr` <- c("園芸学会@千葉大西千葉", 35.6253, 140.1033, "2015-03-28", "2015-03-29", "-")
`_symp_hort2016spr` <- c("園芸学会@東京農大本厚木", 35.4325, 139.3457, "2016-03-26", "2016-03-27", "-")
`_symp_hort2017spr` <- c("園芸学会@日本大藤沢", 35.3804, 139.4688, "2017-03-19", "2017-03-20", "-")

# Others
`_symp_botany2014` <- c("植物学会@明治大生田", 35.613543, 139.548751, "2014-09-12", "2017-09-14", "-")
`_symp_ecol2017` <- c("日本生態学会大会@早稲田大", 35.7087, 139.7196, "2017-03-14", "2017-03-18", "-")

# Interanational
`_symp_lightsym2012` <- c("LightSym2012@Wageningen Univ (The Netherlands)", 51.985223, 5.663653, "2015-07-19", "2015-07-23", "")
`_symp_greensys2015` <- c("GreenSys2015@University of Evora (Portugal)", 38.573125, -7.905660, "2015-07-19", "2015-07-23", "")
`_symp_auspheno2016` <- c("ICEC|AusPheno2016@CSIRO (Australia)", -35.273162, 149.115286, "2016-07-19", "2015-07-23", "")

convert_symp_log_to_df <-
  function(symp_log){
    matrix(symp_log) %>%
    t %>%
    as_data_frame %>%
    set_names(c("name", "lat", "lng", "from", "to", "url")) %>%
    mutate(lat = as.numeric(lat), lng = as.numeric(lng))
  }

`_symp_log` <-
  ls(pattern = "^_symp") %>%
  map(get) %>%
  map_df(convert_symp_log_to_df) %>%
  mutate(popup = paste(name, "<br/>", from, "--", to))

map_symp <-
  leaflet(`_symp_log`) %>% 
  addTiles() %>%
  addMarkers(lng = ~lng, lat = ~lat, popup = ~popup)
```
