---
title: "データフレームからのベクトル出力"
date: 2016-03-20
---

```{r setup, eval = TRUE, echo = FALSE, message= F}
library(dplyr)
library(magrittr)
```

### dplyr::selectでvector出力はできない (メモ

```{r ok1}
# デフォルトの列選択
iris[, "Species"] %>%
  head

# データフレーム構造を維持
iris[, "Species", drop = F] %>%
  head
```

と同じイメージで`dplyr::select`でデータフレームからベクトルを取り出そうとして、よく怒られる  
```{r error1, error = T}
iris %>%
  select(Species, drop = T)
```

[Hadley Wickham (dplyrの作成者) が書いている](http://stackoverflow.com/questions/21618423/extract-a-dplyr-tbl-column-as-a-vector)とおり、`dplyr::select`にはデータフレームからベクトルを出力する仕様はない

上のページを見ていると、「`magrittr::extract2`が便利だよ」とあった  
```{r ok2}
iris %>%
  magrittr::extract2(5) %>%
  head

iris %>%
  magrittr::extract2("Species") %>%
  head
```


複数列に対する挙動が変なので`extract2`の中身を見てみたら、がっかりした  
```{r ok3}
iris %>%
  magrittr::extract2(4:5)
print(extract2)
```

#### 参考  
[Extract a dplyr tbl column as a vector (Stack Overflow)](http://stackoverflow.com/questions/21618423/extract-a-dplyr-tbl-column-as-a-vector)  

```{r info}
devtools::session_info()
```