---
title: "学振SPDの面接へ"
date: 2016-12-06
---

学振SPDの面接を受けてきた <FONT color="green">(不採用 2016-12-26)</FONT>  
自分もwebから情報を得たので、有益そうなことをまとめる  

「すーぱーぽすどく」、だと思っていたけど、実際には「Superlative Postdoctoral Fellow」が正しいらしい [<sup>1</sup>](https://www.jsps.go.jp/english/e-pd/)  

#### 前情報

今年の農学分野のPDの審査結果は

before 

- 申請者数: 206
- 採用内定予定者数: 24
    - うちSPD面接候補者数: 8
- 面接候補者数: 17
- 不採用者: 165

<FONT color="green">
after 
</FONT>

- 申請者数: 206
- 採用内定者数: 28
    - うちSPD内定者数: 2
- 補欠者数: 6
- 不採用者: 172

- SPD面接での合格者は2/8
- PD面接では合格者が4/17・補欠採用者が6/17


例年のSPD採用者数は、各分野で0--2人  
0人の年もあることから、分野内の相対評価だけではない  
各分野最大2名の上限があって、全体採用数が決まっている...？  
候補者が8人だから、倍率は4倍からスタート

#### 準備する

- 面接の要綱をよく読む

> (2017年採用開始版)  
> 
> 面接審査は関連する分科細目を組み合わせて審査を行いますので、次の事項について、ノートパソコンを用いてわかりやすく、簡潔・明瞭に説明してください。  
> 面接開始後8分が経過した時点でアラームが鳴ります。アラームが鳴ったら出来るだけ速やかに説明を終えてください。  
> (1) これまでの研究業績  
> (2) 今後の研究計画は以下の点を踏まえ、研究目的及び研究の特色を具体的に述べてください。  
> 1. 所属研究室(または研究グループ)の研究と、申請者自身が取り組む研究との関係・分担について明らか にしてください。共同研究を行う場合も同様に説明してください。  
> 2. 申請者自身のアイデアやオリジナリティーについて述べてください。  
> 3. 研究の課題(問題点)及び解決方法について説明してください。  
> (3) 審査員との質疑応答(12分以内) 質疑応答の時間に限りがありますので、審査員の質問には出来るだけ簡潔に回答願います。また、面接開始後19分が経過した時点でも終了時間の目安としてアラームが鳴ります。  
> 注) 採用申請書提出後の研究進捗状況や研究業績などについても、質問されることがあります。  

- webで調べた限り、DC・PDの面接と文言は同一で、時間だけが変わっている
    - 「とくにSPDにはこれを！」という要求はなく、全体のクオリティが高いことが求められる？


#### 会場へ

- 受付の後、控え室へ
    - プロジェクタがあって試写ができる
    - ちょうど試写している農学の人がいて、筆頭論文XX報とか書いてあって「まじかよ」ってなる


#### 面接へ

- 氏名を名乗り、課題名を読んでから、計時スタート
    - タイトルページ込みでスライド９枚で挑んだ
    - 8分のアラームがなる前に終わった (7分50秒あたり)
- 審査員は７名前後 (うろ覚え)
    - 自分から7--8 m 程度の距離間
    - 存外に皆さん若く、気鋭の教授陣といった雰囲気
        - おじいちゃん先生はいなかった
        - 面識のある先生もいなかった
    - 農学の８課題を同一メンバーが審査する
        - 審査員の先生の専門はかなりばらつきがあるはず
        - 質疑の感じだと、専門分野がかぶっている人はいなかった
- 質疑 (12分) は圧迫ということもなく普通の質疑
    - 失うものがないので気負わず答えられた
    - 「これができるとどのくらいいいことがある？」
    - 「３年間でどのくらいまでいきそう？」
    - たぶん、19分のアラームも鳴らずに終了


#### 参考ページ  
<sup>1</sup>Research Fellowships for Young Scientists  

<br>
次の締切は、博士論文の教務課への提出 (12/15)