---
title: "RでDropboxからファイルを読み込む"
date: 2016-04-30
---

```{r setup, eval = TRUE, echo = FALSE, message= F}
require(MASS)
require(ggplot2)
require(RColorBrewer) 
require(grid)
require(plyr)
require(dplyr)
require(reshape2)
require(xlsx)
require(knitr)
require(gtable)
require(foreach)
require(gridExtra)
require(magrittr)
require(agricolae)
require(stringr)
require(data.table)
require(lubridate)
require(scales)
require(pforeach)
require(devtools)
require(tidyr)
require(slackr)
require(RCurl)
opts_chunk$set(eval = TRUE,
               error = FALSE,
               prompt = FALSE,
               message = FALSE,
               echo = TRUE,
               fig.hight = 4,
               fig.width = 10,
               warning =FALSE)
```

RでDropboxからデータを読み込む (メモ  
いつも忘れるので  

* ブラウザで該当ファイルをshare状態にする  
* URL linkをコピーし末尾の`?dl=0`を`?raw=1`に変更する  

```{r}
# コーヒーを飲んだ回数
CoffeeCount <-
  "https://www.dropbox.com/s/7afq54mpz4xk1b3/Sample.csv?raw=1" %>%
  url %>%
  read.csv 

CoffeeCount %>%
  mutate(Beginning_of_the_Week = ymd(Beginning_of_the_Week)) %>%
  ggplot(aes(x = Beginning_of_the_Week, y = CoffeeCount)) +
  geom_point() +
  geom_line()
```

アップロードもしたい場合にはパッケージを使う必要がある    

### 参考ページ  
[Read .csv file from dropbox and plot it on leaflet map in shiny app (Stack Overflow)](http://stackoverflow.com/questions/35931923/read-csv-file-from-dropbox-and-plot-it-on-leaflet-map-in-shiny-app)  

```{r info}
devtools::session_info()
```