---
title: "波長に応じた色でプロットする (R"
date: 2017-08-22
---

研究でしばしば波長に関係するデータを出すため、波長に応じた色でプロットしたい場合が多い。

波長から色の変換の各種定数は、[このページ](http://www.natural-science.or.jp/article/20160513143413.php)から。文字列から色コードへの変換が汚いが、いちおうOK。

#### 関数

```{r function, eval = T, echo = T, warning = F, message = F, cash = T}
library(tidyverse)
library(stringr)

lambda2color <-
  Vectorize(
    function(lambda){
      # central wavelength [nm]
      central <- 
        c(red = 700.0,
          green = 546.1,
          blue = 435.8,
          orange = 605.0,
          yellow = 580.0,
          cyan = 490.0,
          purple = 400.0)
  
      # half width [nm]
      half_width <-
        c(red = 90,
          green = 80,
          blue = 80,
          orange = 60,
          yellow = 50,
          cyan = 50,
          purple = 40)
  
      # intensity of seven colors
      intensity <-
        c(red = .95,
          green = .74,
          blue = .75,
          orange = .40,
          yellow = .10,
          cyan = .30,
          purple = .30)
  
      norms <-
        intensity * exp( - (lambda - central)^2 / half_width^2)
      
      r <- sum(norms[c("red", "orange", "purple")])
      g <- sum(norms[c("green", "orange", "yellow", "cyan", "purple")] * c(1, .715, .83, 1, .5))
      b <- sum(norms[c("blue", "orange", "cyan", "purple")] * c(1, .23, 1, 1))
      
      r_8bit <- min(255, round(r*255, 0))
      g_8bit <- min(255, round(g*255, 0))
      b_8bit <- min(255, round(b*255, 0))
      
      # to hexadecimal
      
      to_hex <-
        function(x){
          hexed <-
            as.hexmode(x) %>%
            as.character
          if(str_count(hexed) == 1){
            paste0("0", hexed) %>% return
          } else {
            hexed
          }
        }
      
      # #rrggbb
      paste0("#", to_hex(r_8bit), to_hex(g_8bit), to_hex(b_8bit)) %>%
        return
    }
  )

color_scale_bar <-
  function(wavelength, y, ...){
    lapply(wavelength, function(i){
      annotate(geom = "point", x = i, y = y, col = lambda2color(i), ...)
    })
  }
```

#### デモ

```{r demo, echo = T}
test_df <-
  data_frame(wavelength = 400:800, value = sin(wavelength/2 / pi))

test_df %>%
  ggplot(aes(x = wavelength, y = value, col = factor(wavelength))) +
  guides(col = F) +
  geom_point() +
  geom_line(aes(group = NA)) +
  scale_color_manual(values = lambda2color(test_df$wavelength))

test_df %>%
  ggplot(aes(x = wavelength, y = value)) +
  guides(col = F) +
  geom_point() +
  geom_line(aes(group = NA)) +
  color_scale_bar(wavelength = 400:800, y = -1)
```


#### 参考ページ  

[光の波長からRGBを算出する関数の定義](http://www.natural-science.or.jp/article/20160513143413.php)  

```{r info}
devtools::session_info()
```